# Generated by Django 3.1.5 on 2021-01-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patriot_cadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='perp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='patriot_cadapp.suspect'),
        ),
    ]
