# Generated by Django 3.1.5 on 2024-11-15 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patriot_cadapp', '0004_call_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
