# Generated by Django 3.1.5 on 2024-11-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patriot_cadapp', '0005_call_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_to_call',
            field=models.BooleanField(default=False),
        ),
    ]
